### ISSUE TITLE
[Discussion] Converting GAPIC based libraries to TypeScript

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2821]
Greetings folks!  I wanted to start a conversation about converting our GAPIC based libraries to TypeScript, and figured this was as good a spot as any :)   Just to get the ball rolling, I tried converting the [nodejs-logging](https://github.com/googleapis/nodejs-logging) repository over to TypeScript.  You can see the initial results (with most of the tests passing) here:

https://github.com/googleapis/nodejs-logging/pull/111

I think if we want to do this, we need to address the following issues:

- [ ] **Eliminate the lazy constructor pattern**.  We've discussed this at great length, but before doing *anything*, we need to make the breaking change to get rid of this pattern:

```js
function Logging(options) {
  if (!(this instanceof Logging)) {
    return new Logging(options);
  }
  ....
}
```
We can make this change today, independent of the TypeScript transition. It will likely be semver major. 

- [ ] **Create a TypeScript GAPIC generator.**.  I was really hopeful that I could use the `[allowJs](https://www.typescriptlang.org/docs/handbook/compiler-options.html)` compiler flag in TypeScript to fake out the generated code.  Sadly, you cannot mix the `allowJs: true` and `declaration: true` flags in `tsconfig.json`.  This means that we can't have a `d.ts` file, which really eliminates half the TypeScript appeal. By creating a separate TypeScript focused generator, we can also upgrade our repositories one at a time, ensuring we do things slowly and carefully.  

- [ ] **Do the normal TypeScript conversion dance** After we've fixed the constructor pattern issue, and generated a TypeScript focused GAPIC layer, the rest is well understood.

![convert to typescript](http://i0.kym-cdn.com/photos/images/newsfeed/000/572/078/d6d.jpg)

- [ ] Convert all *.js files to *.ts files
- [ ] Install `typescript` and `gts`, get the initial compilation passing 
- [ ] Convert `var` to `let` and `const`
- [ ] Convert to es6 classes
- [ ] Add initial types where possible
- [ ] Enable noImplicitAny
- [ ] Enable noImplicitThis
- [ ] Eat cake 🍰 

I'm really just putting all this here as a conversation starter.  Thoughts? Concerns? Opinions? 

@GoogleCloudPlatform/node-team @alexander-fenster @theacodes @ofrobots @crwilcox

**Comment by jmdobry** [comment]
Missed a step:

- [ ] - Can generate API reference documentation (to be published on cloud.google.com) for libraries written in TypeScript. [Current docs](http://cloud.google.com/nodejs/docs/reference/libraries)

**Comment by crwilcox** [comment]
I personally am a big fan of TypeScript. I have used it quite a bit and
find it does help as the code base expands and helps to guard against
coding mistakes.

 Right now I can think of two questions:
1) Since I don't have the background, is there data to support doing this
work? Are users asking for d.ts files today? I am guessing yes as there are
some typings files out in the wild today.
2) Is there a benefit to making a new TypeScript generator that we wouldn't
get from extending the generator to emit a .d.ts file to go with the JS we
generate today? As we provide libraries, at least on the surface, it seems
to me providing .d.ts files is what client library users need. But maybe
there is a pro to full conversion I am glossing over?

I think for the handwritten clients could benefit from transitioning to
TypeScript, but I am not sure the generator output matters as much.

**Comment by alexander-fenster** [comment]
I'm starting to think it might be a good idea to connect this request and the in-language generator initiative by @lukesneeringer (see the [Python generator](https://github.com/googleapis/gapic-generator-python) for example). I would say, regardless of converting the existing GAPIC generator templates to TypeScript, if we fund the in-language generation for JavaScript, it should definitely emit TypeScript code.

**Comment by JustinBeckwith** [comment]
@alexander-fenster @lukesneeringer @timburks just wanted to check - any chances of TypeScript landing in the generator in Q3?  We are getting a *lot* of customer demand.

**Comment by JustinBeckwith** [comment]
We have a plan going here 👍
