### ISSUE TITLE
Choose a single code formatter

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2842]
Throughout our various repositories, we use a variety of code formatters:
- Prettier
- Semistandard
- clang-format

Across TypeScript and JavaScript, samples and libraries, it would be ideal to standardize on a single one.  My initial instinct is to use clang-format because it works well enough with `gts`, but I'm just tossing ideas.  Thoughts?

Please vote your choice 😄 

[![](https://api.gh-polls.com/poll/01CH69P7BW6Q47Y8J6VMV24V6M/Prettier)](https://api.gh-polls.com/poll/01CH69P7BW6Q47Y8J6VMV24V6M/Prettier/vote)
[![](https://api.gh-polls.com/poll/01CH69P7BW6Q47Y8J6VMV24V6M/clang-format)](https://api.gh-polls.com/poll/01CH69P7BW6Q47Y8J6VMV24V6M/clang-format/vote)

After this has at least 10 folks chiming in, we'll make a call.

**Comment by JustinBeckwith** [comment]
cc @GoogleCloudPlatform/node-team @GoogleCloudPlatform/yoshi-nodejs @jmdobry @fhinkel

**Comment by ofrobots** [comment]
`clang-format` is used by `gts` because that's what we use internally at Google for TypeScript code. It has the benefit that it works for other languages, and that internal and external Google code use the same format. The negatives are that it is relatively inflexible, is very very slow to pick up new features (e.g. ability to format TSX code), is written in C++, and shipped as a binary that doesn't work in all environments node works.

I would be open to a suggestion of changing the default formatter in `gts` if we have _strong_ motivation to do so.

I think one of the most fundamental requirements is that the formatter should be able to support both JS and TS. Based on that criteria only `prettier` and `clang-format` should be contenders.

**Comment by JustinBeckwith** [comment]
Honestly, `clang-format` has mostly just stayed out of my way.  I would be personally happier with `prettier`, but I don't think I have any actual good reasons at this stage to switch. 

I voted above to switch everything to clang, but *want to hear from everyone*. 

@jmdobry @fhinkel @crwilcox @kinwa91 @theacodes @alexander-fenster

**Comment by JustinBeckwith** [comment]
Making sure @stephenplusplus and @callmehiphop get to chime in here as well :)

**Comment by ofrobots** [comment]
One more negative for `clang-format` is that it is not human-friendly. If there are style errors, it outputs XML rather than human readable error messages. Now it could be argued that one should never need to look at the formatting errors, but I am still not sure if that excuses the user-unfriendliness.

**Comment by kjin** [comment]
I like `prettier` as a format better, but like @ofrobots said there is the benefit of being consistent internal and external to Google. I haven't seen a full evaluation of how important that is to us.

Re: Inflexibility, aren't we (Google) the authors of our own `clang-format` style? Can we influence the changes there?

**Comment by ofrobots** [comment]
> Re: Inflexibility, aren't we (Google) the authors of our own clang-format style? Can we influence the changes there?

In theory yes. In practice, most of the folks on this thread (that have a stake in this) are much more likely to contribute changes to a JS/TS project rather than one written in C++. AFAIK, TS support in clang-format is maintained mostly single-handedly (by @mprobst). Things like TSX support, e.g., are probably not high in the priority list for internal Google stuff, but may be important for external users and for docs and samples we provide for Google Cloud.

**Comment by mprobst** [comment]
There are two things - changing `clang-format` style (e.g. in bin packing, brace spacing, etc), and adding support for more languages.

The tricky bit about changing the style is that it's often hard to find a formatting style that is accepted by at least the large majority of users. I personally don't actually care all that much - as long as it's not eye bleeding terrible, I'm happy to have some consistent style that's automatically enforced. But some people care a lot, and `clang-format` should cater to those users. We're handling that mostly on a case by case basis.

The other question is stuff like adding TSX support. `clang-format` formats many different languages (C++, Java, proto buffers, etc), and is based on LLVM's clang project, i.e. at the very base on a  C++ lexer. That's working surprisingly well, but adding support for entirely different lexing environments, such as TSX's HTML content, would be a major project, and more than we currently want to invest I'm afraid.

I wouldn't actually be opposed to replacing our use of `clang-format` with prettier. We looked into it a bit though, and there are a number of issues that'd make it hard. There are a few breaking issues, such as prettier de-quoting quoted properties, which breaks Closure Compiler optimizations, but also just a long list of style differences that somebody would need to work through and reconcile with Google's JavaScript and TypeScript style. Again, possible, but also a lot of work that's hard to justify, given that `clang-format` currently mostly works for our use cases.

Does that make sense?

**Comment by carnesen** [comment]
ts-style has switched to prettier https://github.com/google/ts-style/pull/259

**Comment by JustinBeckwith** [comment]
This is actually complete 🥂
