### ISSUE TITLE
Add Node.js 12 to the CI

### ISSUE THREAD

**Issue by JustinBeckwith** [googleapis/google-cloud-node#2923]
Looks like Node.js 12 was just released!  Let's get it added to the kokoro configs.

**Comment by JustinBeckwith** [comment]
@bcoe please work with @jkwlui on getting this added :)

**Comment by bcoe** [comment]
@jkwlui @JustinBeckwith I'd like to roll out the `.npmrc` updates too; tldr, @jkwlui please sync up with me before we start rolling this out, and we can use the bulk repo update tool.

**Comment by nolanmar511** [comment]
Is the trampoline image for Node 12 available?

**Comment by nolanmar511** [comment]
Friendly ping: How is progress on this going?

**Comment by JustinBeckwith** [comment]
@bcoe I think it's probably a good time to roll this out

**Comment by bcoe** [comment]
@JustinBeckwith I've been somewhat patiently waiting an update to V8, because there's an odd bug related to test coverage that I'm hoping is fixed up stream ... this is something we can look at prioritizing in the not too distant future.

@jkwlui is the trampoline image available? we just reference the canonical ones through nvm right?

**Comment by nolanmar511** [comment]
I tried to add tests using a Node 12 trampoline image. As of 7/8, the last time I tried to start running this test, I don't think the image was available (kokoro config is [here](https://github.com/google/pprof-nodejs/blob/c1598672b6ca55e1e6ea3b3906169dc2a1c6c77f/tools/kokoro/unit-test/continuous-linux-node12.cfg#L6))

**Comment by bcoe** [comment]
Node 12 is now available and tested.
