### ISSUE TITLE
google cloud run Error during WebSocket handshake: Unexpected response code: 400

### ISSUE THREAD

**Issue by codersmoon** [googleapis/google-cloud-node#2965]
i use google cloud run for nodejs app (chat app with socket io) ;but i get this error :

` Error during WebSocket handshake: Unexpected response code: 400`

I get error only once and my app works perfectly;

this is my client side :  `const socket = io('/my-namespace');`

**Comment by JustinBeckwith** [comment]
Greetings!  Google Cloud Run does not support websockets:
https://github.com/ahmetb/cloud-run-faq#are-websockets-supported-on-cloud-run

This repository is used to track issues specific to the Google Cloud Node.js Client Libraries.  Since this is more of a Cloud Run specific issue, it would be awesome if you could file an issue here in the public issue tracker:
https://issuetracker.google.com/issues/new?component=608076&template=0

cc @steren :)
