### ISSUE TITLE
Why are we deleting these libraries from libraries.json?

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-cloud-node#3023]
PR #3022 seems to be deleting some important libraries from the json file. It may be an issue with this query: https://github.com/googleapis/google-cloud-node/blob/master/bin/generate-readme.js#L126.

We should investigate to see what is going on with that document generation.

**Comment by JustinBeckwith** [comment]
So I have a suspect here, and it is me.  Looking at this code:
https://github.com/googleapis/google-cloud-node/blob/master/bin/generate-readme.js#L127

That's what is responsible for regenerating this file, and it's hooked into synthtool.  We should run that code, and dump a log of all found libraries. Now when I wrote that code, what I *didn't* know is that it's possible for the search API to not be entirely exhaustive: 
https://docs.github.com/en/rest/reference/search#timeouts-and-incomplete-results

If it turns out that the `incomplete_results` property is getting set to `true`, we need to re-work this code to:
- fetch all repositories in the organization, using pagination ([example](https://docs.github.com/en/rest/reference/repos#list-organization-repositories))
- perform a filter on the combined results, removing archived, non-TypeScript/non-JavaScript repos, archived repos, etc

**Comment by JustinBeckwith** [comment]
I think you fixed this :)
