### ISSUE TITLE
Turn off trusted-contributor bot for release-please

### ISSUE THREAD

**Issue by chingor13** [googleapis/google-cloud-node#3355]
We expect release-please to keep an open PR with pending changes to be released. We do not need to run samples/system tests until we are ready to publish the packages. Otherwise, we will be running so many unnecessary integration tests when we are not ready to release.

When a maintainer is ready to release:
1. approve the PR
2. comment with `/gcbrun`
3. add the `automerge` label

**Comment by sofisl** [comment]
I don't love this solution, because it feels like an obscure process that will be difficult to maintain/socialize and people will easily get confused as to why PRs aren't merging. I'm not a fan of doing one-off processes.

I wonder if we can create a new 'freeze-tag' label that would stop tests from running on PRs? Or, what if we have release-PRs released as draft PRs, and don't run tests on draft PRs? That will make it obvious to the user that the PR needs to be converted before merging.

**Comment by sofisl** [comment]
Let's reopen this when it becomes a problem, and we can reevaluate our options then. (feel free to reopen if you want to continue discussing this).
