### ISSUE TITLE
We should update the repo field in the .repo-metadata.json file to reflect the subdirectory

### ISSUE THREAD

**Issue by sofisl** [googleapis/google-cloud-node#3477]
Fixes #3466 and #3450

@bcoe, is there anything else that consumes this field? Would it be alright to change it to add the subdirectory?

**Comment by bcoe** [comment]
@sofisl I would add this information to the `package.json` rather than `repo-metadata.json`, here's an example of what I've seen other projects do:

https://www.npmjs.com/package/@types/yargs

Note that the [homepage](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#homepage) path points to the subdirectory in the mono-repo, rather than the top level.

Seems like a good convention that other mono-repos follow in the community.
