### ISSUE TITLE
What format are the language keys?

### ISSUE THREAD

**Issue by ollydixon** [googleapis/google-cloud-node#3524]
I can't seem to find anything on the documentation, which is insufficient.

Are the language keys i18n?

Also, does this have typescript support? Might help with knowing what format values are.

**Comment by sofisl** [comment]
Hi @ollydixon, here is some documentation on [language keys](https://cloud.google.com/translate/docs/languages).

We release libraries as TS libraries. So, you can always check the types in the generated code (for [example](https://github.com/googleapis/google-cloud-node/blob/fa12e5db80735e93b0434b1eb3ab4b814058db96/packages/google-cloud-translate/src/v2/index.ts#L190)). I think, since we've released v3, we don't have v2 protos out, which makes it so we don't have TS service if you just use v2. If you use v3, you'll see TS support (for reference, that method - detectLanguage in v3 - its return type is documented here, and should also be available if you install the v3 library: https://github.com/googleapis/google-cloud-node/blob/fa12e5db80735e93b0434b1eb3ab4b814058db96/packages/google-cloud-translate/protos/protos.d.ts#L951).

If you wouldn't mind reopening another issue with the bug (and code to reproduce), that would be greatly appreciated. Thank you!

**Comment by ollydixon** [comment]
@sofisl I’ve been using typescript since alpha :-)

When I hover over the language keys type it needs to tell me the standard it’s using. I shouldn’t need to hunt documentation that’s impossible to find. Google does docs really badly.

**Comment by sofisl** [comment]
Hi @ollydixon,

Thanks for your feedback. To clarify your question, are you saying that these docs are not [sufficient](https://cloud.google.com/translate/docs/languages), or that the information in these docs should be present in the TS definitions?

If the former, I'd encourage you to open a bug directly with the docs directly, as it's a slightly different team that deals directly with these products (I would open it for you, but I'm not quite sure in which ways the documentation isn't specific enough).

<img width="1312" alt="Screenshot 2023-02-08 at 10 13 31 AM" src="https://user-images.githubusercontent.com/55454395/217616565-835e4b0d-9d62-42e8-bc8f-279e2661ea10.png">

If the latter, I'd request that you kindly specify what you feel is missing in the documentation, and I can open a bug internally so that our autogenerated libraries can receive your wording. If this is the case, feel free to reopen this same bug.

Lastly, when I said the following: 

```
If you wouldn't mind reopening another issue with the bug (and code to reproduce), that would be greatly appreciated. Thank you!
```` 
I was referring to your comment here:

```
There also seems to be a bug. This is clearly two languages, but only shows as one.
```

I don't know what code you used to get this behavior, so it would be great if you could open it up with a new bug.

Thanks again for your feedback.

**Comment by ollydixon** [comment]
@sofisl over the +7 years I've been using Google Cloud no one has ever replied, fixed or taken my feedback seriously using the feedback feature, you might as well ask me to talk to a wall.

When I hover over the language keys it needs to tell the developer the standard it's using, that simple, very basic TypeScript functionality.

For example, these keys we get, which standard does this library use here?
<img width="542" alt="Screenshot 2023-02-08 at 19 20 52" src="https://user-images.githubusercontent.com/6940726/217618086-b7ff3842-8ed5-4107-8af9-a1af97d12036.png">

--

Regarding the code used to for the bug, I linked a screenshot into the app, I even have the debugger hovering over the code.. I showed you the code there.. you can copy paste from the screenshot (on Mac)

The fact that you closed this without even reading it is terrible.

**Comment by ollyde** [comment]
Here is the code copied from the screenshot, sorry Linux and Windows users.

```
// Imports the Google Cloud client library
const { Translate } = require( '@google-cloud/translate').v2;
const translate = new Translate();

export async function detectLanguage (text: string): Promise<any> {
    let [detections] = await translate.detect text);
    detections = Array.isArray (detections) ? detections : [detections];

    detections = detections.filter((d) => d.confidence > 0.5);
    const keys = detections.map((d) => .language);
    return keys;
}
```

**Comment by ollyde** [comment]
The sentence is 
'This is test content. Jeg snakker litt Norsk'

Two languages, Norsk and English.

@sofisl 
Now I had to guess the language key cause I don't know the format, it could have been 1 of 11 results. No way to match it up accurately on the client.

Now you see how this 1 bug.

**Comment by sofisl** [comment]
Hi @ollyde, thank you for clarifying your questions. If I can summarize, it seems like you'd like the following:

1) For TS definitions to include the standard of the response ([ISO-639](https://cloud.google.com/translate/docs/languages)).

2) To look into the bug as you've described above, i.e., only one language being returned (thank you for clarifying that the code you showed was the same one that produced the unexpected result).

Does that summarize your concerns? If so, I think the two bugs you've opened seem appropriate.

**Comment by ollyde** [comment]
@sofisl the definition needs to be on the function call so that the IDE can tell us. 

As I said before the TypeScript supplied by Google is of weird quality, missing definitions and is way over engineered which is two things that shouldn't exist together 

:-)
