### ISSUE TITLE
Cannot specify "quantity" when calling the prediction API of "add-to-cart"

### ISSUE THREAD

**Issue by hemmachat** [googleapis/google-cloud-node#3640]
Hi there,

We are using your client library to connect to the Retail API to get the recommendations. When we call the function `client.predict(payload)`, the library is complaining about the missing `quantity` of the product which already been specified. The same payload works with cURL and normal HTTP request with fetch library. I suspect there is something wrong with protobuf serialisation or the schema. Thank you for looking into it.

Here is the payload:
```json
{
  "placement": "projects/aaa/locations/global/catalogs/default_catalog/placements/recommended-for-you",
  "filter": "filterOutOfStockItems",
  "validateOnly": false,
  "userEvent": {
    "eventType": "add-to-cart",
    "visitorId": "1111",
    "userInfo": {
      "userId": "222"
    },
    "productDetails": [
      {
        "product": {
          "id": "333"
        },
        "quantity": 1
      }
    ]
  }
}
```

Here is the error message:
```
/Users/xxx/Downloads/yyy/node_modules/@grpc/grpc-js/build/src/call.js:31
    return Object.assign(new Error(message), status);
                         ^

Error: 13 INTERNAL: Request message serialization failure: .google.cloud.retail.v2beta.ProductDetail.quantity: object expected
```

#### Environment details

  - OS: OSX
  - Node.js version: 16.13.1
  - npm version: 8.1.2
  - `@google-cloud/retail` version: 1.7.0

**Comment by sofisl** [comment]
@robmorgan-tab, thanks for posting the solution! I think the correct way of writing it is:

`"quantity": {"value": 1}` (although it seems numberValue works as well, not sure why)

I'm not quite sure it's a bug, if we go back to the [protos](https://raw.githubusercontent.com/googleapis/google-cloud-node/main/packages/google-cloud-retail/protos/protos.d.ts) for UserEvent, it expects a nested object `ProductDetail` which looks like this:

```
                interface IProductDetail {

                    /** ProductDetail product */
                    product?: (google.cloud.retail.v2.IProduct|null);

                    /** ProductDetail quantity */
                    quantity?: (google.protobuf.IInt32Value|null);
                }
```
That type looks like:

```
        interface IInt32Value {

            /** Int32Value value */
            value?: (number|null);
        }
```

If we look back to the protos, you'll notice it's set as a [protobuf.Int32Value](https://github.com/googleapis/google-cloud-node/blob/3370cf17724fdf1d233c49cb155db68e26227abf/packages/google-cloud-retail/protos/google/cloud/retail/v2/user_event.proto#L298), instead of just a regular `int32` 

(see for example a [regular int32](https://github.com/googleapis/google-cloud-node/blob/3370cf17724fdf1d233c49cb155db68e26227abf/packages/google-cloud-retail/protos/google/cloud/retail/v2/user_event.proto#L315))

I'm not quite sure the API designed it this way, but it seems the generator is representing their desired type faithfully. I'll close this for now, but if you think this bug deserves more action, please feel free to reopen with desired steps! Thanks!

**Comment by sofisl** [comment]
After looking into it some more, it seems that the protobuf.Int32Value accepts a null value, whereas an int32 would just default to 0; so, it uses a [wrapper type to distinguish null from 0](https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/wrappers.proto).

If you want to not have to use this `value` property, you can use the `proto3-json-serializer` library:

```

import * as serializer from 'proto3-json-serializer';
import {protobuf} from 'google-gax';

...
const root = protobuf.Root.fromJSON(require('@google-cloud/whatever/build/protos/protos.json'));
const RequestType = root.lookupType('google.cloud.whatever.v1.RequestType');
const request = serializer.fromProto3JSON(RequestType, {quantity: 1});
```
