### ISSUE TITLE
typeless-sample-bot adding export() statement in JS conversion

### ISSUE THREAD

**Issue by kweinmeister** [googleapis/google-cloud-node#3994]
A TypeScript prototype was created [here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3029) for `nodejs-docs-samples`.

Everything is working properly, except the generated JS file fails lint checks. There is an extra `export();` statement added to the end of the converted JS file. See this [diff](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/3029/files#diff-0fb06e782b9a2987a7530672bbe85ddba25818b654ae84b9727f6f871cb78f16).

**Comment by feywind** [comment]
@kweinmeister That's really strange. I think Babel must be doing this for some reason, and I'll try to figure out why.

I see that there's a pretty complex owlbot.py there, and I wonder if we can simplify it a bit. You'll also want the latest typeless bot version, which I've been pulling in manually in my primary test repo:

https://github.com/googleapis/nodejs-pubsub/pull/1666/files#diff-5ffcc5c595bdb5127f82e03dbcdb1eeb75a2633f6f44b7f640f9d7523bc0f264

Ahh, I see @bcoe commented there too :) Basically while I've had it in more rapid development, this has saved me a long roundtrip through synthtool reviews and releases, but it's my intent to get the latest one folded back in, since it's getting to a stable point. For testing, you might want to try installing the newest manually for now.

**Comment by feywind** [comment]
Okay, I figured out what's going on here. Basically your sample has both `import` and `require` so Babel gets confused and assumes it's a standard Node module (which needs some kind of export, even if it's `{}`).

The way I've fixed this in my own samples is to expand the sample tags. This will be needed anyway, if you want proper TypeScript support, e.g.:

https://github.com/googleapis/nodejs-pubsub/blob/main/samples/typescript/getSchema.ts

```typescript
// [START pubsub_get_schema]
/**
 * TODO(developer): Uncomment this variable before running the sample.
 */
// const schemaNameOrId = 'YOUR_SCHEMA_NAME_OR_ID';

// Imports the Google Cloud client library
import {PubSub} from '@google-cloud/pubsub';

// Creates a client; cache this for further use
const pubSubClient = new PubSub();
```

So the `import` is part of the sample, and you can import everything there. (And again I think people will need to use `import` for a real sample anyhow.)

This does cause one complication, which is that samples end up without any "immediate mode" code. I hope users could figure that out though?

I'll link you to a TypeScript style guide I've been working on, in email.

Maybe there's enough here that it'd be better to meet on it and hash it out.

**Comment by kweinmeister** [comment]
Thanks, all of the information was really helpful! I now have the lint checks passing. I will resume the conversation via email, so we can close this issue.
