### ISSUE TITLE
Unable to export 'deviceModel' using the @google-analytics/data Client

### ISSUE THREAD

**Issue by DesAWSume** [googleapis/google-cloud-node#4849]
I am using @google-analytics/data (https://www.npmjs.com/package/@google-analytics/data)

The way i export the data is using 
```
const [response] = await analyticsDataClient.runReport({
    property: `properties/${propertyId}`,
    dateRanges: [
      {
        startDate: '2023-11-26',
        endDate: '2023-11-27',
      },
    ],
    dimensions: [
      { name: 'deviceCategory' },
      { name: 'deviceModel' },
      {name : 'date'}
    ],
    metrics: [
      { name: 'activeUsers' },
      { name: 'newUsers' },
      { name: 'screenPageViews' },
    ]
```
There is no DeviceModel data from the response

I constructed the data in a table format
here is the output 
<img width="811" alt="image" src="https://github.com/googleapis/google-cloud-node/assets/7110636/97f5fdec-e0f7-472b-b9fe-6555fbab994e">

The console showing 
![Xnip2023-11-28_14-21-43](https://github.com/googleapis/google-cloud-node/assets/7110636/504c46f9-2567-4bce-a52a-d7c6cbb28f26)

**Comment by ikuleshov** [comment]
Hello,

The issue is unlikely to be specific to the client library implementation, as the output contains the "deviceModel" dimension "(not set)", which is a correct value. There can be [multiple reasons](https://support.google.com/analytics/answer/13504892) why a dimension can be "(not set)". 

The following troubleshooting steps might help:

1) Only compare identical reports using API vs UI. In your case, the UI report seems different, so it is hard to compare against.

2) Use the [API Explorer](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/properties/runReport?apix=true) to run your query directly and inspect the response text. This will eliminate any possible quirks in the client library implementation and your code.

For any general product and API-related questions, please refer to the [Data API: Getting Help](https://developers.google.com/analytics/devguides/reporting/data/v1/help) page.
