### ISSUE TITLE
What kind of errors are specifically set in "failureReason"?

### ISSUE THREAD

**Issue by lbk-yuuki-nakamura** [googleapis/google-cloud-node#5524]
### Please make sure you have searched for information in the following guides.

- [X] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
- [X] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
- [X] Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq
- [X] Check our libraries HOW-TO: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md
- [X] Check out our authentication guide: https://github.com/googleapis/google-auth-library-nodejs
- [X] Check out handwritten samples for many of our APIs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### Documentation Request

The document below states "Output only. If and only if action's state is FAILED a failure reason is set."

https://cloud.google.com/php/docs/reference/cloud-dataform/latest/V1beta1.WorkflowInvocationAction

Probably the implementation location is below.

https://github.com/googleapis/google-cloud-java/blob/1d97e4db6d5106aad8fed2386151c457e0258de3/java-dataform/proto-google-cloud-dataform-v1beta1/src/main/java/com/google/cloud/dataform/v1beta1/WorkflowInvocationAction.java#L2422

It is difficult to read what kind of error is set from the source code, so please tell me the specific setting value.

**Comment by sofisl** [comment]
Hi @lbk-yuuki-nakamura, thank you for submitting your question! This question relates to the API specifically, so unfortunately this channel isn't the best place for it (we deal with the libraries themselves, and the documentation you point at comes from the API itself, and isn't handwritten).  That being said, I did a quick search and also couldn't find the answer (inlcuding in our protos), so I think the API team would be best to answer this themselves. Feel free to submit your question [here](https://issuetracker.google.com/savedsearches/6274893), and in the meantime I'll move this question to discussion so that others in the community can help answer. Thanks again!
