### ISSUE TITLE
TextToSpeech Stream (StreamingSynthesizeRequest) Documentation

### ISSUE THREAD

**Issue by brunocarneiro** [googleapis/google-cloud-node#5707]
### Please make sure you have searched for information in the following guides.

- [X] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
- [X] Check our Troubleshooting guide: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/troubleshooting
- [X] Check our FAQ: https://googlecloudplatform.github.io/google-cloud-node/#/docs/guides/faq
- [X] Check our libraries HOW-TO: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md
- [X] Check out our authentication guide: https://github.com/googleapis/google-auth-library-nodejs
- [X] Check out handwritten samples for many of our APIs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### Documentation Request

Hello,

I'm trying to use the new method `ttsClient.streamingSynthesize` but unsuccessfully. The error I'm getting is:
"Malordered Data Received. Expected streaming_config but received input. Send exactly one config, followed by text input"

After checking the [documentation](https://github.com/googleapis/google-cloud-node/blob/main/packages/google-cloud-texttospeech/samples/generated/v1/text_to_speech.streaming_synthesize.js#L50), the [PR](https://github.com/googleapis/google-cloud-node/pull/5620) and the [unit test](https://github.com/googleapis/google-cloud-node/blob/a8d513d66e58983a3ac9e4726f6229bc58eb753b/packages/google-cloud-texttospeech/test/gapic_text_to_speech_v1.ts#L430) of the version `"@google-cloud/text-to-speech": "5.4.0"` I couldn't find any example of the `StreamingSynthesizeRequest` populated. Also could not find any tts stream sample [here](https://github.com/GoogleCloudPlatform/nodejs-docs-samples).

Here is part of my code:
```
            const request = {
                streamingConfig: { voice: { languageCode: 'es-es', name: 'es-ES-Polyglot-1' } },
                input: { text: '¡hola!' }
              };
            
            const stream = await client.streamingSynthesize();
            stream.on('data', (response) => this.onData(response));
            stream.on('error', (err) => reject(err));
            stream.on('end', () => resolve());
            stream.write(request);
            stream.end();
```

**Comment by sofisl** [comment]
Hi @brunocarneiro,

Thanks for your question. Since these libraries are mostly autogenerated, this documentation request is not something we can fulfill (it needs to be done either by the API, or it needs a handwritten sample). 

- If this is a question, please submit your question to text-to-speech  [here](https://cloud.google.com/support/docs/issue-trackers)). You can also submit it as a question to our Discussions tab to engage our community.
- If this is a request for handwritten documentation, please submit it to googleapis/nodejs-docs-samples.
- Although this isn't quite the same, there is an example for streaming with text-to-speech that seems to have the config [slightly differently](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/HEAD/speech/recognize.js)

**Comment by utrolig** [comment]
Like @brunocarneiro mentioned, the example does not work and gives the following error:
```
Malordered Data Received. Expected streaming_config but received input. Send exactly one config, followed by text input
```

I've tried writing a `streaming_config` config first before writing the `request` object, but it's still the same error.
